package GUI;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;

/**
 *
 * @author Joe
 */
public class ServicesUI extends javax.swing.JFrame {

    public JButton getAddServicesButton() {
        return AddServicesButton;
    }

    public void setAddServicesButton(JButton AddServicesButton) {
        this.AddServicesButton = AddServicesButton;
    }

    public JButton getBackButton() {
        return backButton;
    }

    public void setBackButton(JButton backButton) {
        this.backButton = backButton;
    }

    public JCheckBox getWiFiChckBox() {
        return WiFiChckBox;
    }

    public void setWiFiChckBox(JCheckBox WiFiChckBox) {
        this.WiFiChckBox = WiFiChckBox;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JCheckBox getGymBox() {
        return gymBox;
    }

    public void setGymBox(JCheckBox gymBox) {
        this.gymBox = gymBox;
    }

    public JCheckBox getHammamBox() {
        return hammamBox;
    }

    public void setHammamBox(JCheckBox hammamBox) {
        this.hammamBox = hammamBox;
    }

    public JCheckBox getPoolBox() {
        return poolBox;
    }

    public void setPoolBox(JCheckBox poolBox) {
        this.poolBox = poolBox;
    }

    public JCheckBox getAllHotelBox() {
        return allHotelBox;
    }

    public void setAllHotelBox(JCheckBox allHotelBox) {
        this.allHotelBox = allHotelBox;
    }

    public JCheckBox getAllInBox() {
        return allInBox;
    }

    public void setAllInBox(JCheckBox allInBox) {
        this.allInBox = allInBox;
    }

    public JCheckBox getAllTourBox() {
        return allTourBox;
    }

    public void setAllTourBox(JCheckBox allTourBox) {
        this.allTourBox = allTourBox;
    }

    public JCheckBox getCliffsBox() {
        return cliffsBox;
    }

    public void setCliffsBox(JCheckBox cliffsBox) {
        this.cliffsBox = cliffsBox;
    }

    public JCheckBox getGiantsBox() {
        return giantsBox;
    }

    public void setGiantsBox(JCheckBox giantsBox) {
        this.giantsBox = giantsBox;
    }

    public JCheckBox getWawBox() {
        return wawBox;
    }

    public void setWawBox(JCheckBox wawBox) {
        this.wawBox = wawBox;
    }
 
    /**
     * Creates new form ServicesUI
     */
    public ServicesUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        WiFiChckBox = new javax.swing.JCheckBox();
        AddServicesButton = new javax.swing.JButton();
        gymBox = new javax.swing.JCheckBox();
        poolBox = new javax.swing.JCheckBox();
        hammamBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        allInBox = new javax.swing.JCheckBox();
        allTourBox = new javax.swing.JCheckBox();
        allHotelBox = new javax.swing.JCheckBox();
        wawBox = new javax.swing.JCheckBox();
        giantsBox = new javax.swing.JCheckBox();
        cliffsBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Services"));

        WiFiChckBox.setText("*WiFi");
        WiFiChckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WiFiChckBoxActionPerformed(evt);
            }
        });

        AddServicesButton.setText("Continue to checkout");
        AddServicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddServicesButtonActionPerformed(evt);
            }
        });

        gymBox.setText("*Gym");
        gymBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymBoxActionPerformed(evt);
            }
        });

        poolBox.setText("*Pool");
        poolBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poolBoxActionPerformed(evt);
            }
        });

        hammamBox.setText("*Hammam");
        hammamBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hammamBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Add services for your stay or continue to checkout");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        allInBox.setText("All in package (All Servcies)");
        allInBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allInBoxActionPerformed(evt);
            }
        });

        allTourBox.setText("All Tour servcies");
        allTourBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTourBoxActionPerformed(evt);
            }
        });

        allHotelBox.setText("All hotel services");
        allHotelBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allHotelBoxActionPerformed(evt);
            }
        });

        wawBox.setText("Wild atlantic way");
        wawBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wawBoxActionPerformed(evt);
            }
        });

        giantsBox.setText("Giants Causeway");
        giantsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giantsBoxActionPerformed(evt);
            }
        });

        cliffsBox.setText("Cliffs of Moher");
        cliffsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliffsBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("€150-00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("€160-00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("€11-00");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("€50-00");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("€60-00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("€50-00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("€5-00");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("€2-00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setText("€3-00");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("€1-00");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setText("*Charged per night stayed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allInBox)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allHotelBox)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poolBox)
                                    .addComponent(WiFiChckBox)
                                    .addComponent(hammamBox)
                                    .addComponent(gymBox)
                                    .addComponent(backButton))))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(47, 47, 47)
                                            .addComponent(jLabel6))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wawBox)
                                    .addComponent(giantsBox)
                                    .addComponent(cliffsBox)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddServicesButton)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(allTourBox))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allInBox)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allTourBox)
                    .addComponent(allHotelBox)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WiFiChckBox)
                    .addComponent(wawBox)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poolBox)
                    .addComponent(giantsBox)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hammamBox)
                    .addComponent(cliffsBox)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gymBox)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddServicesButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void hammamBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hammamBoxActionPerformed
        // TODO add your handling code here:
        allInBox.setSelected(false);
        allHotelBox.setSelected(false);
    }//GEN-LAST:event_hammamBoxActionPerformed

    private void AddServicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddServicesButtonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_AddServicesButtonActionPerformed

    private void allInBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allInBoxActionPerformed
            boolean allIn = this.getAllInBox().isSelected();
            if(allIn){
                allHotelBox.setSelected(false);
                allTourBox.setSelected(false);
                WiFiChckBox.setSelected(false);
                poolBox.setSelected(false);
                hammamBox.setSelected(false);
                gymBox.setSelected(false);
                wawBox.setSelected(false);
                giantsBox.setSelected(false);
                cliffsBox.setSelected(false);              
            }                           
    }//GEN-LAST:event_allInBoxActionPerformed

    private void allHotelBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allHotelBoxActionPerformed
        // TODO add your handling code here:
        //boolean allHotel = this.getAllHotelBox().isSelected();
        //if(allHotel){
            allInBox.setSelected(false);
            WiFiChckBox.setSelected(false);
            poolBox.setSelected(false);
            hammamBox.setSelected(false);
            gymBox.setSelected(false);
    }//GEN-LAST:event_allHotelBoxActionPerformed

    private void allTourBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTourBoxActionPerformed
        // TODO add your handling code here:
            allInBox.setSelected(false);
            wawBox.setSelected(false);
            giantsBox.setSelected(false);
            cliffsBox.setSelected(false);
    }//GEN-LAST:event_allTourBoxActionPerformed

    private void WiFiChckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WiFiChckBoxActionPerformed
        // TODO add your handling code here:
        allInBox.setSelected(false);
        allHotelBox.setSelected(false);
    }//GEN-LAST:event_WiFiChckBoxActionPerformed

    private void poolBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poolBoxActionPerformed
        // TODO add your handling code here:
        allInBox.setSelected(false);
        allHotelBox.setSelected(false);
    }//GEN-LAST:event_poolBoxActionPerformed

    private void gymBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymBoxActionPerformed
        // TODO add your handling code here:
        allInBox.setSelected(false);
        allHotelBox.setSelected(false);
    }//GEN-LAST:event_gymBoxActionPerformed

    private void wawBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wawBoxActionPerformed
        // TODO add your handling code here:
        
        allInBox.setSelected(false);
        allTourBox.setSelected(false);
    }//GEN-LAST:event_wawBoxActionPerformed

    private void giantsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giantsBoxActionPerformed
        // TODO add your handling code here:
        allInBox.setSelected(false);
        allTourBox.setSelected(false);
    }//GEN-LAST:event_giantsBoxActionPerformed

    private void cliffsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliffsBoxActionPerformed
        // TODO add your handling code here:
        allInBox.setSelected(false);
        allTourBox.setSelected(false);
    }//GEN-LAST:event_cliffsBoxActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddServicesButton;
    private javax.swing.JCheckBox WiFiChckBox;
    private javax.swing.JCheckBox allHotelBox;
    private javax.swing.JCheckBox allInBox;
    private javax.swing.JCheckBox allTourBox;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cliffsBox;
    private javax.swing.JCheckBox giantsBox;
    private javax.swing.JCheckBox gymBox;
    private javax.swing.JCheckBox hammamBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox poolBox;
    private javax.swing.JCheckBox wawBox;
    // End of variables declaration//GEN-END:variables
}
